multimap {
  # Hate-and-Junk Addresses
  hatenjunk_envfrom {
    type = "from";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/hate-and-junk.csv";
    symbol = "HATENJUNK_ENVFROM";
    description = "Envelope From is a Hate-and-Junk address";
    score = 10.0;
  }

  hatenjunk_envrcpt {
    type = "rcpt";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/hate-and-junk.csv";
    symbol = "HATENJUNK_ENVRCPT";
    description = "Envelope Recipient is a Hate-and-Junk address";
    score = 10.0;
    one_shot = true;
  }

  hatenjunk_from {
    type = "header";
    header = "from";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/hate-and-junk.csv";
    symbol = "HATENJUNK_FROM";
    description = "From is a Hate-and-Junk address";
    score = 10.0;
  }

  hatenjunk_to {
    type = "header";
    header = "To";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/hate-and-junk.csv";
    symbol = "HATENJUNK_TO";
    description = "To is a Hate-and-Junk address";
    score = 1.0;
    one_shot = true;
  }

  hatenjunk_cc {
    type = "header";
    header = "Cc";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/hate-and-junk.csv";
    symbol = "HATENJUNK_CC";
    description = "To is a Hate-and-Junk address";
    score = 10.0;
    one_shot = true;
  }

  hatenjunk_replyto {
    type = "header";
    header = "Reply-To";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/hate-and-junk.csv";
    symbol = "HATENJUNK_REPLYTO";
    description = "Reply-To is a Hate-and-Junk address";
    score = 10.0;
  }

  hatenjunk_mdn {
    type = "header";
    header = "Disposition-Notification-To";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/hate-and-junk.csv";
    symbol = "HATENJUNK_MDN";
    description = "Disposition-Notification-To is a Hate-and-Junk address";
    score = 10.0;
  }

  .include(try=true,priority=5) "${DBDIR}/dynamic/multimap.conf"
  .include(try=true,priority=1,duplicate=merge) "$LOCAL_CONFDIR/local.d/multimap.conf"
  .include(try=true,priority=10) "$LOCAL_CONFDIR/override.d/multimap.conf"
}
