multimap {
  # Scam Addresses
  scammail_envfrom {
    type = "from";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/scam.csv";
    symbol = "SCAMMAIL_ENVFROM";
    description = "Envelope From is a Scam address";
    score = 10.0;
  }

  scammail_envrcpt {
    type = "rcpt";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/scam.csv";
    symbol = "SCAMMAIL_ENVRCPT";
    description = "Envelope Recipient is a Scam address";
    score = 10.0;
    one_shot = true;
  }

  scammail_from {
    type = "header";
    header = "from";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/scam.csv";
    symbol = "SCAMMAIL_FROM";
    description = "From is a Scam address";
    score = 10.0;
  }

  scammail_from_address {
    type = "header";
    header = "from";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/user_lists/scam-mail.csv";
    symbol = "SCAMMAIL_FROM";
    description = "From is a Scam address";
    score = 10.0;
  }

  scammail_to {
    type = "header";
    header = "To";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/scam.csv";
    symbol = "SCAMMAIL_TO";
    description = "To is a Scam address";
    score = 1.0;
    one_shot = true;
  }

  scammail_cc {
    type = "header";
    header = "Cc";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/scam.csv";
    symbol = "SCAMMAIL_CC";
    description = "To is a Scam address";
    score = 10.0;
    one_shot = true;
  }

  scammail_cc_address {
    type = "header";
    header = "Cc";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/user_lists/scam-mail.csv";
    symbol = "SCAMMAIL_CC";
    description = "To is a Scam address";
    score = 10.0;
    one_shot = true;
  }

  scammail_replyto {
    type = "header";
    header = "Reply-To";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/scam.csv";
    symbol = "SCAMMAIL_REPLYTO";
    description = "Reply-To is a Scam address";
    score = 10.0;
  }

  scammail_replyto_address {
    type = "header";
    header = "Reply-To";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/user_lists/scam-mail.csv";
    symbol = "SCAMMAIL_REPLYTO";
    description = "From is a Scam address";
    score = 10.0;
  }

  scammail_mdn {
    type = "header";
    header = "Disposition-Notification-To";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/scam.csv";
    symbol = "SCAMMAIL_MDN";
    description = "Disposition-Notification-To is a Scam address";
    score = 10.0;
  }

  .include(try=true,priority=5) "${DBDIR}/dynamic/multimap.conf"
  .include(try=true,priority=1,duplicate=merge) "$LOCAL_CONFDIR/local.d/multimap.conf"
  .include(try=true,priority=10) "$LOCAL_CONFDIR/override.d/multimap.conf"

}
