multimap {
  # Scam Addresses
  suspiciousmail_envfrom {
    type = "from";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/suspicious.csv";
    symbol = "SUSPICIOUSMAIL_ENVFROM";
    description = "Envelope From is a Scam address";
    score = 1.5;
  }

  suspiciousmail_envrcpt {
    type = "rcpt";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/suspicious.csv";
    symbol = "SUSPICIOUSMAIL_ENVRCPT";
    description = "Envelope Recipient is a Scam address";
    score = 1.5;
    one_shot = true;
  }

  suspiciousmail_from {
    type = "header";
    header = "from";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/suspicious.csv";
    symbol = "SUSPICIOUSMAIL_FROM";
    description = "From is a Scam address";
    score = 1.5;
  }

  suspiciousmail_to {
    type = "header";
    header = "To";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/suspicious.csv";
    symbol = "SUSPICIOUSMAIL_TO";
    description = "To is a Scam address";
    score = 1.0;
    one_shot = true;
  }

  suspiciousmail_cc {
    type = "header";
    header = "Cc";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/suspicious.csv";
    symbol = "SUSPICIOUSMAIL_CC";
    description = "To is a Scam address";
    score = 1.5;
    one_shot = true;
  }

  suspiciousmail_replyto {
    type = "header";
    header = "Reply-To";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/suspicious.csv";
    symbol = "SUSPICIOUSMAIL_REPLYTO";
    description = "Reply-To is a Scam address";
    score = 1.5;
  }

  suspiciousmail_mdn {
    type = "header";
    header = "Disposition-Notification-To";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/avidansternberg/project-blocklist/refs/heads/master/domain_lists/suspicious.csv";
    symbol = "SUSPICIOUSMAIL_MDN";
    description = "Disposition-Notification-To is a Scam address";
    score = 1.5;
  }

  .include(try=true,priority=5) "${DBDIR}/dynamic/multimap.conf"
  .include(try=true,priority=1,duplicate=merge) "$LOCAL_CONFDIR/local.d/multimap.conf"
  .include(try=true,priority=10) "$LOCAL_CONFDIR/override.d/multimap.conf"
}
